### ISSUE TITLE
Typescript Import Error

### ISSUE THREAD

**Issue by PaitoAnderson** [planttheidea/moize#104]
I got an error importing moize in TypeScript, although it did work fine.

Error:
<img width="1076" alt="Screen Shot 2019-04-12 at 11 16 39 AM" src="https://user-images.githubusercontent.com/4108718/56047965-85fa1900-5d14-11e9-8638-f1b0cc459165.png">

Opening up the typing file I noticed this error:
<img width="753" alt="Screen Shot 2019-04-12 at 11 16 28 AM" src="https://user-images.githubusercontent.com/4108718/56047953-7e3a7480-5d14-11e9-9d12-002cb8bef0cf.png">

My thought here is we could just change that to:
`export default moize;` or wrap everything in a `declare module` with export default.

I'll send a PR for your review.

**Comment by PaitoAnderson** [comment]
@planttheidea Thanks for merging, cutting a release and all!

**Comment by planttheidea** [comment]
@PaitoAnderson no worries, thanks for the PR! Makes it easy. :smiley:
