### ISSUE TITLE
onExpire sends wrong arguments?

### ISSUE THREAD

**Issue by kamronbatman** [planttheidea/moize#108]
I created a moize.default() with an onExpire. The idea was to have the onExpire call a function to refill the cache.  The original memoized function takes one optional argument.
It looks like the onExpire callback is receiving an empty array instead of `undefined`.

I am confused, but shouldn't the onExpire essentially receive the same arguments as the original function? Maybe some spread operator is missing?

**Comment by kamronbatman** [comment]
Here is an example of my workaround:
https://github.com/vyng/truecaller-node/blob/77792a97ab3a214d8e035324e2c689d0be19110a/lib/fetchPublicKeys.js#L32

**Comment by planttheidea** [comment]
The `onExpire` method receives the key for the cache value that is expiring, so if it's receiving an empty array that means the cached value expiring is for a call based on no arguments passed. You said that the function receives one optional argument, so it seems to be based on calling it without that argument.

Keep in mind that calling a function with no parameters is different than explicitly calling a function with `undefined`. We used the `arguments` object for the call to determine the key, and that is dynamically populated based on the specific values passed, not married to any static declarations in the function parameters

**Comment by kamronbatman** [comment]
I see. This is an interesting fact. You are right, the base case is that nothing is passed.

**Comment by planttheidea** [comment]
Something you may consider is using default parameters instead of coalescing in the body. The default parameter would then be the key and help cache more effectively.

**Comment by kamronbatman** [comment]
@planttheidea, I was using default parameters before and that is why I changed it.

**Comment by kamronbatman** [comment]
Yes, that didn't work as well.

**Comment by planttheidea** [comment]
Alright well I can investigate this a little more in the coming days. I'm actually in the midst of a complete rewrite in Typescript, so the timing is good. If you could describe what you are seeing vs what you expect to see that would help.

**Comment by kamronbatman** [comment]
Here is a "safe" version:
```javascript
// lib/fetchPublicKey.js

const { promisify } = require('util');
const request = promisify(require('request'));
const pemtools = require('pemtools');
const moize = require('moize');

const publicKeyUrl = 'https://api4.truecaller.com/v1/key';

const internalFetchPublicKeys = async (url) => {
  console.log('URL', url);
  const { body } = await request({
    url: url,
    method: 'GET',
    json: true,
  });

  if (!Array.isArray(body) || body.length === 0) {
    throw Error(`Invalid public key received from ${url}`);
  }

  return body.map(({ key }) => (
    pemtools(Buffer.from(key, 'base64'), 'PUBLIC KEY').pem
  ));
};

const fetchPublicKeys = moize.default(
  internalFetchPublicKeys,
  {
    maxAge: 1000, // 1000 * 60 * 30, // 30 minutes,
    isPromise: true,
    // Due to a bug, make this work:
    onExpire: (params) => fetchPublicKeys(params),
  },
);

module.exports = (url = publicKeyUrl) => fetchPublicKeys(url);
```

Importing and running `fetchPublicKeys('https://www.halpme.com')` should output
`URL: https://www.halpme.com` every second.

Instead I get an array with the string in it, per above.

**Comment by planttheidea** [comment]
Oh man okay haha that's easy, it's how you're calling it.

`onExpire: (params) => fetchPublicKeys(...params)`

The array is the list of arguments originally passed, so when you get them just spread to recreate the same call.

**Comment by kamronbatman** [comment]
yeah, so maybe a quick documentation update is needed, cause that wasn't clear to me initially. haha

**Comment by planttheidea** [comment]
Sure, sorry I misunderstood because the "workaround" was how it actually worked haha. I can improve the documentation to be clearer about what is being passed and give a simple example about how to re-call as was done here.

If you have any other questions, don't hesitate!
