### ISSUE TITLE
Issues getting moize working with got

### ISSUE THREAD

**Issue by rfgamaral** [planttheidea/moize#117]
Hi there,

I'm trying to get `moize` working with [`got`](https://github.com/sindresorhus/got) by creating a wrapper class around `got` which abstracts the usage of `moize`, but I'm having some issues and I'm not sure what's wrong.

Take the following `moize.ts` file:

```typescript
import { URLSearchParams } from 'url';

import got, { Got } from 'got';
import moize from 'moize';

type QueryStringParams =
    | Record<string, string | number | boolean | null>
    | URLSearchParams
    | string;

abstract class RESTDataSource {
    private httpClient: Got;

    constructor(prefixUrl: string) {
        const gotInstance = got.extend({
            prefixUrl,
        });

        this.httpClient = moize(gotInstance, {
            isPromise: true,
            maxAge: 5000,
            onCacheAdd: cache => {
                console.log('ADD', cache.keys);
            },
            onCacheHit(cache) {
                console.log('HIT', cache.keys);
            },
        });
    }

    protected async get<T>(path: string, params?: QueryStringParams): Promise<T> {
        return this.httpClient<T>(path, {
            method: 'GET',
            resolveBodyOnly: true,
            responseType: 'json',
            searchParams: params,
        });
    }
}

class RocketsAPI extends RESTDataSource {
    constructor() {
        super('https://api.spacexdata.com/v3/');
    }

    async getRocketById(id: string): Promise<any> {
        return this.get(`rockets/${id}`);
    }
}

const rocketsApi = new RocketsAPI();

rocketsApi.getRocketById('falcon1');
```

Executing this script with `npx ts-node moize.ts` I get the following output:

```
ADD [
  [
    'rockets/falcon1',
    {
      method: 'GET',
      resolveBodyOnly: true,
      responseType: 'json',
      searchParams: undefined,
      url: 'rockets/falcon1'
    }
  ]
]
HIT [
  [
    'rockets/falcon1',
    {
      method: 'GET',
      resolveBodyOnly: true,
      responseType: 'json',
      searchParams: undefined,
      url: 'rockets/falcon1'
    }
  ]
]
```

My first problem is that I have a single request (the cache should be empty), yet `onCacheHit` was called. I don't think this should've happened, right?

Next, let's add a second identical request, like this:

```ts
(...)
rocketsApi.getRocketById('falcon1');
rocketsApi.getRocketById('falcon1');
```

Executing the script with this change results in the following output:

```
ADD [
  [
    'rockets/falcon1',
    {
      method: 'GET',
      resolveBodyOnly: true,
      responseType: 'json',
      searchParams: undefined,
      url: 'rockets/falcon1'
    }
  ]
]
ADD [
  [
    'rockets/falcon1',
    {
      method: 'GET',
      resolveBodyOnly: true,
      responseType: 'json',
      searchParams: undefined,
      url: 'rockets/falcon1'
    }
  ],
  [
    'rockets/falcon1',
    {
      method: 'GET',
      resolveBodyOnly: true,
      responseType: 'json',
      searchParams: undefined,
      url: 'rockets/falcon1'
    }
  ]
]
HIT [
  [
    'rockets/falcon1',
    {
      method: 'GET',
      resolveBodyOnly: true,
      responseType: 'json',
      searchParams: undefined,
      url: 'rockets/falcon1'
    }
  ],
  [
    'rockets/falcon1',
    {
      method: 'GET',
      resolveBodyOnly: true,
      responseType: 'json',
      searchParams: undefined,
      url: 'rockets/falcon1'
    }
  ]
]
HIT [
  [
    'rockets/falcon1',
    {
      method: 'GET',
      resolveBodyOnly: true,
      responseType: 'json',
      searchParams: undefined,
      url: 'rockets/falcon1'
    }
  ],
  [
    'rockets/falcon1',
    {
      method: 'GET',
      resolveBodyOnly: true,
      responseType: 'json',
      searchParams: undefined,
      url: 'rockets/falcon1'
    }
  ]
]
```

This is even more confusing... First, `onCacheAdd` was called twice, but the keys are the same, it should've been called just once (for the first request). Second, `onCacheHit` was called twice too (but this is probably related to my first problem) and on both times it was hit, it printed the keys twice.

I have tried to add `isDeepEqual: true`, but the result was exactly the same. I'm not sure exactly what's wrong but I have a feeling it's related to how `moize` is calculating/matching/serializing the keys. However, I'm not sure what's the recommended course of action here adn/or if I'm doing something wrong.

**Comment by planttheidea** [comment]
You are correct that the resulting observations are not correct (at least not the standard output of `moize`), however something may be afoot with `got` itself. For example, the first observation (both `ADD` and `HIT` should up with the single call) is an impossible codepath unless the method is called twice. There are two distinct possibilities with cache changes:
- `onCacheAdd` + `onCacheChange`
- `onCacheHit` + optional `onCacheChange` if matching index is non-zero

A couple of recommendations to debug further:
- Add an `onCacheChange`. Does it fire twice? This would lend further evidence to support the underlying method being the issue.
- Instead of wrapping a `got`-based function, wrap a simple function that just does a `console.log` of the arguments. Does the same problem still exist?

I can't look into this personally for a few days, but a simpler repro (with no outside dependencies) would help diagnose things.

**Comment by rfgamaral** [comment]
>     * Add an `onCacheChange`. Does it fire twice? This would lend further evidence to support the underlying method being the issue.

It actually fired 3 times:

```
$ ts-node index.ts
ADD [ [ 'rockets/falcon1',
    { method: 'GET',
      resolveBodyOnly: true,
      responseType: 'json',
      searchParams: undefined,
      url: 'rockets/falcon1' } ] ]
CHANGE [ [ 'rockets/falcon1',
    { method: 'GET',
      resolveBodyOnly: true,
      responseType: 'json',
      searchParams: undefined,
      url: 'rockets/falcon1' } ] ]
HIT [ [ 'rockets/falcon1',
    { method: 'GET',
      resolveBodyOnly: true,
      responseType: 'json',
      searchParams: undefined,
      url: 'rockets/falcon1' } ] ]
CHANGE [ [ 'rockets/falcon1',
    { method: 'GET',
      resolveBodyOnly: true,
      responseType: 'json',
      searchParams: undefined,
      url: 'rockets/falcon1' } ] ]
CHANGE []
Done in 7.66s.
```

If I observed this correctly, the third time was fired after `maxAge` had elapsed.

>     * Instead of wrapping a `got`-based function, wrap a simple function that just does a `console.log` of the arguments. Does the same problem still exist?

Nope, the problem does not exist; `onCacheAdd` fired once, followed by `onCacheChange` and after `maxAge` elapsed, it was fired again with an empty `[]` (just like the example above).

> I can't look into this personally for a few days, but a simpler repro (with no outside dependencies) would help diagnose things.

Here you go: https://github.com/rfgamaral/moize-with-got

**Comment by planttheidea** [comment]
If you were unable to reproduce with a standard function, likely this is a problem with the way `got` it's being used, or the library itself. I can take a look when I get the chance, but if you cannot reproduce without the extra dependency then you may need to file an issue with that package.

**Comment by rfgamaral** [comment]
I already did, it's linked above :)

**Comment by planttheidea** [comment]
Sorry if I was unclear, I mean you may need to file a issue with `got`. The link you provided appears to be a standalone repro, which should help me attempt to reproduce, but is orthogonal to what I was referring to.

**Comment by rfgamaral** [comment]
No, you misunderstood me, or maybe I was the one not clear enough. I didn't meant the link I posted as comment, but this one in the issue timeline:

![image](https://user-images.githubusercontent.com/96476/75708040-eb9e1d80-5cb7-11ea-990c-d7fd8b47cf2a.png)

**Comment by rfgamaral** [comment]
Well, the problem also exists with [`axios`](https://github.com/axios/axios): https://github.com/rfgamaral/moize-with-got/tree/axios

Maybe it's my TypeScript specific implementation causing the issue? Will try something less convoluted and report back in a few.

**Comment by rfgamaral** [comment]
Yep, same thing happens with the following basic example:

```ts
import moize from 'moize';
import got from 'got';

const gotInstance = got.extend({
    prefixUrl: 'https://api.spacexdata.com/v3/',
});

const httpClient = moize(gotInstance, {
    isPromise: true,
    maxAge: 5000,
    onCacheAdd(cache) {
        console.log('ADD', cache.keys);
    },
    onCacheChange(cache) {
        console.log('CHANGE', cache.keys);
    },
    onCacheHit(cache) {
        console.log('HIT', cache.keys);
    },
});

httpClient({
    method: 'GET',
    url: 'rockets/falcon9',
});
```

And the same if I replace `got` with `axios`:

```ts
import moize from 'moize';
import axios from 'axios';

const axiosInstance = axios.create({
    baseURL: 'https://api.spacexdata.com/v3/',
});

const httpClient = moize(axiosInstance, {
    isPromise: true,
    maxAge: 5000,
    onCacheAdd(cache) {
        console.log('ADD', cache.keys);
    },
    onCacheChange(cache) {
        console.log('CHANGE', cache.keys);
    },
    onCacheHit(cache) {
        console.log('HIT', cache.keys);
    },
});

httpClient({
    method: 'GET',
    url: 'rockets/falcon9',
});
```

**Comment by rfgamaral** [comment]
I think it might be related to `isPromise: true` somehow and how `moize` handles promises. I could be wrong, I just took a quick look to the source code.

**Comment by rfgamaral** [comment]
After taking a closer look at the source code, I've reached the following conclusion:

- `moize` uses `micro-memoize` under the hood;
- I'm using `moize` with an HTTP request library (`got`, `axios`, etc.) and setting `isPromise: true`;
- From `micro-memoize` documentation when we have `isPromise: true`:

  > Identifies the value returned from the method as a Promise, which will result in one of two possible scenarios:
  > - **If the promise is resolved, it will fire the onCacheHit and onCacheChange options**
  > - If the promise is rejected, it will trigger auto-removal from cache

Does it look like what I've observed above is expected?

Assuming yes, I'm just confused why does the `onCacheHit` and `onCacheChange` events need to be fired when a promise is resolved. Can you please shed some light on that?

**Comment by planttheidea** [comment]
You know, this is an excellent question. I believe when I wrote that was to notify the consumer of the resolution, but I can see how it would be confusing. Perhaps I can remove that upstream, although that would be a breaking change so I'd need to think hard over that.

That doesn't account for your main problem, which is that multiple calls with identical keys are not treated as cached. Your use of `isDeepEqual` was correct, if that was not working then there may be a bug in the key resolution. As mentioned, it will likely be a few days before I can investigate, but investigate I shall.

**Comment by rfgamaral** [comment]
I guess I'll have to wait for you to have time to investigate this issue. Let me know if I can help with anything else.

In the meantime, what would be the best/simplest way for me to specify the exact cache key to use per request instead of having `moize` calculate it? Based on the documentation I can't understand exactly what I have to do.

**Comment by planttheidea** [comment]
So I've been able to do some investigation into this, and I think I've discovered a few things.

First , you were correct to apply `isDeepEqual: true` to the options. Because you are passing two parameters (the first string url, the second object of options), by default `moize` will use strict equality of each argument to compare key equality. The first always passes, the second always fails because a new object is created each time. By setting `isDeepEqual: true`, it does a deep equality check of the values and _should_ pass. Except it doesn't, because...

Second, it appears that the way you are using `got` (which I guess is just a wrapper around `axois`?) is preventing that from happening. Under the hood, either `got` or `axios` is _mutating_ the options object to include the URL.

```js
got('some/url', { method: 'GET' })
// is originally arguments of
['some/url', { method: 'GET' }]
// but is mutated to become
['some/url', { method: 'GET', url: 'some/url' }];
```

Mutation is the enemy of memoization (and functional programming)! This side effect causes the subsequent calls to fail each time, because the deep equality check fails:

```js
// calling it the next time with
got('some/url', { method: 'GET' });
// fails because
isDeepEqual({ method: 'GET' }, { method: 'GET', url: 'some/url' })
```

So what can you do to work around this? The answer is ... a few different approaches, depending on your project needs.

1) Avoid the shorthand usage of `got` / `axios`, and use the object version.

Modify your call to use the object version:

```js
got('some/url', { method: 'GET' });
// is modified to
got({ method: 'GET', url: 'some/url' });
```

Because this is the "target state" of the library options, no mutation occurs, and the deep equality check passes.

2) Use the `transformArgs` option. _my choice_

If you transform your arguments to be the same end state, the deep equality check should also pass.

```js
const httpClient = moize.promise(gotInstance, {
  isDeepEqual: true,
  onCacheAdd() {...},
  onCacheHit() {...},
  transformArgs(args) {
    const [url, options] = args;

    return [{ ...options, url }];
  }
});
```

This also has the flexibility to work with calls using either the shorthand approach or the normalized approach.

3) Use the `matchesKey` option instead of `isDeepEqual`.

This uses a custom key comparator that you pass, which allows completely custom key equality checks.

```js
const httpClient = moize.promise(gotnstance, {
  onCacheAdd() {...},
  onCacheHit() {...},
  matchesKey(cachedKey, key) {
    const [cachedUrl, cachedOptions] = cachedKey;
    const [url, options] = key;

    const existingUrl = cachedUrl || cachedOptions.url;
    const newUrl = url || options.url;
        
    if (newUrl !== existingUrl) {
      return false;
    }

    for (const key in options) {
      if (key !== 'url' && options[key] !== cachedOptions[key]) {
        return false;
      }
    }

    return true;
  }
```

I personally try to avoid this option as it creates a more brittle setup often leading to more maintenance over time, but it is available if you deem it the best choice for your project.

Any one of those 3 options should allow you to integrate the two libraries in the way you seek.

**Comment by rfgamaral** [comment]
I understand the issue now. It makes sense. :)

I'll look into all of them and pick the one that best suits my needs best.

Thank you so much @planttheidea for investigating this. And sorry for taking so much of your time.

Regards.

**Comment by planttheidea** [comment]
No worries! Glad I could help sort this out. 🤙
