### ISSUE TITLE
Adding map-memo to benchmark

### ISSUE THREAD

**Issue by Venryx** [planttheidea/moize#120]
Have you tried benchmarking any libraries that work similarly to [map-memo](https://github.com/StarryInternet/map-memo)?

I really like the approach it uses (creating chains of `Maps`/`WeakMaps`, using the very fast [internal Javascript hashing](https://v8.dev/blog/hash-code)), and was wondering if any of the libraries in your benchmark used it.

If not, would be cool to have one added for comparison!

----

P.S. I know `Maps`/`WeakMaps` are fundamentally a different kind of hashing -- based on reference rather than contents -- but it would be nice to know which is faster and by how much, for cases where either approach works fine.

For example, my project only needs reference-based hashing/memoization (for object arguments), and switching from `JSON.stringify` keys to instead just hashing the object arguments by adding to chains of `Maps`, drastically improved performance in my project.

I assume that the reference-based hashing is faster than even the very fastest serialization system used by `moize` and its competitors, but it would be nice to confirm this and to see by how much. (And for there to be a note, perhaps, saying that if reference-based hashing is sufficient, that there are faster alternatives using it than those based on serialization which are shown on the main benchmark.)

**Comment by planttheidea** [comment]
Just to be clear, `moize` does not use serialization by default since version 3. It has that option available (`moize.serialize`) but the standard usage is a strict equality comparison of arguments, which is the hash referencing you refer to..

**Comment by Venryx** [comment]
Can you point me to the file where the `Cache` class is defined?

I see a message here: https://github.com/planttheidea/moize/blob/7acde48eb08310914ab896965c2fa5428706d493/CHANGELOG.md#145
```
Switch to using Cache for caching instead of native Map (was previously only used for polyfilling, but is twice as fast ... I feel silly for not testing its performance prior)
```

That sounds like it might be doing the same approach `map-memo` uses, but I'd like to confirm/compare in the source.

**Comment by planttheidea** [comment]
I should also call out that `moize` is now a wrapper around a minimalist memoize library I also wrote, `micro-memoize`. The real `Cache` class lives there.

**Comment by Venryx** [comment]
Interesting.

This function seems to imply that, when searching for the cached-value for a given argument-set, the Cache class walks through an array of previous caches looking for a matching argument-set?
https://github.com/planttheidea/micro-memoize/blob/master/src/Cache.ts#L207

If so, it seems that that would be slower than the approach [map-memo](https://github.com/StarryInternet/map-memo) takes of leveraging the internal Javascript hashing for the lookup of the cached data.

Am I misunderstanding, or is it correct that micro-memoize "searches" for cache-hits, as opposed to using a single hash-based "lookup" as used in `map-memo`. (If that were the case, there'd be a use for both of course -- `micro-memoize` for "by-value" caching, and `map-memo` for faster "by-reference" caching.)

**Comment by planttheidea** [comment]
There are inherent tradeoffs when it comes to `Map` or `WeakMap` support, which have been examined several times over. Things like LRU for cache expiration, prioritization of most recent function calls, etc., that cannot be done with the approach you mention.

This is the beautiful thing about the JS ecosystem; options to satisfy use-cases. If you feel that `map-memo` is a better fit for your project, then u endorse it! It just takes a different architectural direction than what `moize` takes.

**Comment by Venryx** [comment]
> Things like LRU for cache expiration, prioritization of most recent function calls, etc., that cannot be done with the approach you mention.

The two drawbacks listed seem to just be optimizations, though -- optimizations which aren't needed for a cache that uses hash lookups rather than previous-cache-entry iteration, no?
