### ISSUE TITLE
`maxAge` prevents process from exiting

### ISSUE THREAD

**Issue by ehmicky** [planttheidea/moize#122]
When `maxAge` is set, the process does not exit until the `maxAge` timeout has been reached.

```js
import moize from 'moize'

const noop = function () {}
const mNoop = moize(noop, { maxAge: 36e5 })

// The process won't stop for one hour
mNoop()
```

This is because `maxAge` calls `setTimeout()` [here](https://github.com/planttheidea/moize/blob/bb603bdccf86916190eb27a4e238d9f7f55518dd/src/maxAge.js#L100) and [there](https://github.com/planttheidea/moize/blob/bb603bdccf86916190eb27a4e238d9f7f55518dd/src/maxAge.js#L132).

This could be fixed by calling [`id.unref()`](https://nodejs.org/api/timers.html#timers_timeout_unref) on the `id` returned by `setTimeout()`. 

This is Node.js specific. Browsers do not have this problem and do not have the `id.unref()` method.

**Comment by planttheidea** [comment]
This is definitely something worth mentioning in the documentation, appreciate you calling it out. I'll add this to the `README`.

**Comment by ehmicky** [comment]
This seems more like a bug than a documentation miss?

In the example above, the `setTimeout()` should not hold the process alive. This can be done by calling `id.unref()`.

**Comment by planttheidea** [comment]
When and how would it programmatically determine that the timeout should be unset?

**Comment by ehmicky** [comment]
`id.unref()` does not unset the timeout, it just removes the reference. The timeout will still be there, but it won't hold the process alive.

**Comment by planttheidea** [comment]
Oh nice yeah I just saw that in the node documentation as well (sorry it's 6am here haha). Definitely something I can incorporate as a patch. Thanks!

**Comment by ehmicky** [comment]
Thanks!
Please note `id.unref` is `undefined` when not run in Node.js (e.g. in a browser).

**Comment by planttheidea** [comment]
Yup, seems like a simple existy check should suffice. I'll have a PR soon.

**Comment by planttheidea** [comment]
Alright I've created a PR, but I'll be busy for a while. I should be able to merge and publish this later today, though.

**Comment by ehmicky** [comment]
Thanks a lot @planttheidea!
