### ISSUE TITLE
[Feature request] maxSizeRAM

### ISSUE THREAD

**Issue by ambroiseRabier** [planttheidea/moize#136]
The library provide `maxSize` that is described like that:

> The maximum number of values you want stored in cache for this method.

However, I have a use case where I like to limit caching to a **memory size**. Something like `maxSizeRAM: '80mb'`

---

**Here is my use case:**

I am making an React application and I have component more or less like that:

```ts
function MyComponent (props: { inputText: string; inputIndex: number; }) { /* ... */ }
```

The component render some html that get exponentially bigger when `inputIndex` grow . Meaning exponentially slower for the browser. I can start cache/memoize only starting from an high enough index where the rendering become slower with "Conditional memoization usage" solution you provided on https://github.com/planttheidea/moize/issues/124 .
Hovewer the ideal solution would be to limit memory size used.

**Comment by planttheidea** [comment]
JavaScript as a language does not provided a native way to determine memory consumption of a given object. How would you propose measuring this value?

**Comment by ambroiseRabier** [comment]
I think it is screwed, wasn't sure if there was a way to measure memory usage in JS. Well, thanks for the quick reply.
