### ISSUE TITLE
MaxSize default is set to 1

### ISSUE THREAD

**Issue by sagiBarkol** [planttheidea/moize#149]
Documentation says: "maxSize defaults to Infinity"
Oppose to the documentation you can see that the maxSize is set to 1: 

`import { Options } from './types';

/**
 * @private
 *
 * @constant DEFAULT_OPTIONS
 */
export const DEFAULT_OPTIONS: Options = {
    isDeepEqual: false,
    isPromise: false,
    isReact: false,
    isSerialized: false,
    isShallowEqual: false,
    matchesArg: undefined,
    matchesKey: undefined,
    maxAge: undefined,
    maxArgs: undefined,
    maxSize: 1,
    onExpire: undefined,
    profileName: undefined,
    serializer: undefined,
    updateCacheForKey: undefined,
    transformArgs: undefined,
    updateExpire: false,
};`

**Comment by planttheidea** [comment]
The documentation says that [the `maxSize` defaults to `1`](https://github.com/planttheidea/moize#maxsize) ... can you point to where it says it defaults to `Infinity`? This used to be the default, but changed in version 6, so it is entirely possible that I missed a reference to this.

**Comment by sagiBarkol** [comment]
My bad:) I looked at an old documentary on npm, you can close. 
but it took me a while to understand why each key overwrites the last.

**Comment by planttheidea** [comment]
No worries, stale documentation can always be an issue.
