### ISSUE TITLE
Unusable with NestJS

### ISSUE THREAD

**Issue by jrista** [planttheidea/moize#153]
I'm a fan of moize, and have been using it for some time. I started using NestJS heavily this year for a range of microservices, and have started needing memoization. Sadly, it does not appear as though the way this library exports is compatible with NestJS...or perhaps more specifically, the pure JS/Node code it gets compiled into?

When importing like this, using the latest NestJS and Node v14:

`import moize from 'moize';`

That gets compiled into this in the js code (note the lack of the documented `.default` that should be tacked onto the require()):

`const moize_1 = require("moize");`

And the usage ends up being this:

`exports.func = moize_1.default(...);`

Which causes this at runtime:

`TypeError: moize_1.default is not a function`

**Comment by jrista** [comment]
Interestingly, just for kicks, I tried to use require:

`const moize = require('moize').default;`

This compiled to the correct code:

```ts
const moize = require('moize').default;
exports.func = moize(...);
```

However still causes an error:

`TypeError: moize is not a function`

**Comment by planttheidea** [comment]
This actually sounds like NextJS is using either the UMD or CommonJS export and expecting it to have the shape of the ESM export. For context, `moize` has three different files that the `package.json` exposes depending on environment / import style:

- browser => UMD
- module => ESM
- main (general) => CJS

Just curious, but can you alias the import to instead point specifically to the ESM package? Based on [the documentation](https://nextjs.org/docs/advanced-features/module-path-aliases), it looks like that would be done in the config like this:

```json
"compilerOptions": {
  "paths": {
    "moize": "node_modules/moize/dist/moize.esm.js"
  }
}
```

I haven't used NextJS prior so I am speculating (all examples I can find use aliasing for internal paths, not external modules), but I'm curious if that will unblock you.

In the meantime, I can update the documentation for CommonJS usage (a miss from the recent update to v6; the `.default` is no longer required) and can do something I've done in a couple of other projects, which is tack on a dummy self-referring `.default` property to the `moize` function for edge-case cross-compatibility.

**Comment by planttheidea** [comment]
Alright I've just released `6.0.3` with the self-referring property, if you could update to that version and see if that fixes your issue I'd appreciate it.

**Comment by jrista** [comment]
@planttheidea It looks like you looked into neXtjs. I am using neStjs. One is for React, the other is just a Node.js based server platform:

https://nestjs.com

I'm not sure if the changes you made were specific for Next.js, or if they will also work for NestJS.

**Comment by planttheidea** [comment]
Ah, my bad. No, my changes were not exclusive to NextJS ... they should work for any mixed-consumption environment.
