### ISSUE TITLE
Persistent cache

### ISSUE THREAD

**Issue by 174n** [planttheidea/moize#164]
Any plans on implementing a persistent cache? It would be really useful. And there are currently no actively maintained alternatives that do that

**Comment by planttheidea** [comment]
Can you elaborate on what you mean by "persistent cache"?

**Comment by Rundik** [comment]
I meant that the cache won't get lost on application restarts. So for example if I use moize to generate images as buffers, that buffers still there when the app get crashed or the server gets restarted

**Comment by planttheidea** [comment]
This would inherently be dependant on environment, as it would only be possible in some and even within those the implementations vary widely. Likely such specific implementations will never be supported by `moize`, as it is outside the scope of common usage and because it would break it's agnostic nature.

**Comment by Bessonov** [comment]
> Likely such specific implementations will never be supported by moize, as it is outside the scope of common usage and because it would break it's agnostic nature.

Probably, it can be achieved in a more generic way through exposure of some sort of storage api. May be with direct storage or periodical sync, depending on performance or consistency requirements. I think it would be OK, if storage doesn't support all data types.

**Comment by planttheidea** [comment]
I'm not disputing the fact it's possible, however there is always a balance that must exist between something that should be supported natively by the library and what should be borne out of convention.

For example, what if I merely add a `hydrate` method to the existing API for a moized method? This is agnostic, low footprint, and opens up the ability to create a such a cache. I can even provide documented examples with basic `localStorage` use and such.
