### ISSUE TITLE
Import in Typescript environment with NodeJS?

### ISSUE THREAD

**Issue by Emsu** [planttheidea/moize#196]
When I try importing with
`import moize from "moize/mjs/index.mjs";`

I get the following error:
`error TS7016: Could not find a declaration file for module 'moize/mjs/index.mjs'`

It seems like the type file is only found if I `import moize from 'moize';` however the build from that import causes other issues in NodeJS as well.

What's the recommended way to import `moize` via ESM or to configure `tsconfig.json` for an ESM Node environment with Typescript?

**Comment by Emsu** [comment]
Currently it seems to me it might be similar to the issue described here? [https://stackoverflow.com/questions/72457791/typescript-packages-that-ship-with-mjs-and-d-ts-but-without-d-mts-how-to-i](https://stackoverflow.com/questions/72457791/typescript-packages-that-ship-with-mjs-and-d-ts-but-without-d-mts-how-to-i)

Basically the types field is resolving to CommonJS for Typescript but for ESM it's loading the .mjs file without types which is leading to Typescript with an ESM import to fail? Does that sound plausible?

**Comment by planttheidea** [comment]
Yeah it's the same issue as experienced with `micro-memoize`. I'll try to add a fix for it later tonight like I did there.

**Comment by planttheidea** [comment]
This should be fixed with the `6.1.6` release. Let me know if you have any more issues!
