### ISSUE TITLE
Typing isn't exposed

### ISSUE THREAD

**Issue by vhfmag** [planttheidea/moize#45]
So, my bad, but even though the typing is defined, it isn't exposed to Typescript, since I didn't mention it in package.json...

I can work on it if want asap, but it's really no trouble. There should simply be a property named 'types' at the package.json directing to the type definitions file (`"types": "./index.d.ts",`, in this case).

**Comment by planttheidea** [comment]
So should I change the `typings` property to `types`? Or should both exist?

**Comment by vhfmag** [comment]
Oh, I didn't remember I included any property whatsoever. Just changing the property to types should work (https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html). Thank you!

**Comment by planttheidea** [comment]
Released as part of `2.5.1`. Any more issues, lemme know!
