### ISSUE TITLE
[Documentation] Clarify deprecated statement

### ISSUE THREAD

**Issue by afitzek** [planttheidea/moize#47]
https://github.com/planttheidea/moize#cache states that:

```
The default cache implementation is build for speed in its purpose, however if you would like then you can pass in a custom cache implementation. This will be deprecated in the next major release.
```

Could you clarify what exactly will be deprecated in the next major release. The default implementation or the possibility to provide a custom cache implementation? Thx.

**Comment by planttheidea** [comment]
What will be deprecated is the ability pass in a custom cache implementation. The default cache implementation is getting more and more targeted to the specific cache usage (for performance and footprint reasons) and the requirements for providing a custom cache implementation are getting more specific as such. There are a number of ways to manipulate the default cache for specific needs, and I will likely expand on that flexibility when this deprecation occurs, however there is a lot of conditional code internally that checks to see if the cache is custom or not that can be done away with to improve performance and simplify the logic.

That said, you are the first person to even discuss the custom cache option, so I assume it is highly unused. If enough users tell me that they use the custom cache implementation, I can be swayed to not deprecate it. And either way, trust me ... v3 is a ways off.

**Comment by planttheidea** [comment]
So ... I stand corrected, at least about v3 being a ways off. I was struck with an idea about better cache key construction / retrieval, and it let me to a pretty large rearchitecture of cache as a whole ... and definitely not something where custom cache can slide in. When I release v3 in the next day or so, the `cache` option will be no more. On the bright side, the changes made `moize` just stupid fast ... 3x faster when using multiple parameters, 10x faster on React components. It basically blows everything else I can find out of the water.

I'm closing this as I think that I answered your question, but also it will be a moot point in the next day or so from a documentation perspective. If you have any other questions, though, let me know!
