### ISSUE TITLE
[Feature] Can we update maxAge or force expiration?

### ISSUE THREAD

**Issue by Redsandro** [planttheidea/moize#66]
1. Is it possible to reset the `maxAge` counter every time a cached value is accessed? E.g. keep it in memory for the full [`maxAge`] when it is accessed within [`maxAge`].  
E.g. `maxAgeReset = true // defaults to false`  
We'd have to store the timeOuts from `expireAfter()` in the hashing table in order to be able to clearTimeout them and re-run `expireAfter()` on that key.
2. Can we have an `onGet` or `forceExpire` callback that is called when a cached value exists but before it is returned, so we can do some checks, and return `true` or `false` to indicate wether or not the cache should be forced to expire and a new value should be calculated?

__1__ would keep extending the expiration time until it is not accessed before `maxAge` or __2__ returns `true`.

(Although technically in case of __2__ it would still extend the expiration time as a new value is calculated.)

**Comment by planttheidea** [comment]
Closing, as this should have been taken care of with #67 and #70, both of which have been released in `4.0.0`.
