### ISSUE TITLE
Items added manually to the cache are not expired

### ISSUE THREAD

**Issue by ntamas** [planttheidea/moize#76]
Items that are added manually to the cache do not expire automatically and they also do not purge older items from the cache if the size limits are exceeded. I am not sure whether this is a bug or it is the intended behaviour; if this is intended, I think it should be documented somewhere.

Let me describe my use-case. I have a web service where I can submit object IDs and the service returns the corresponding objects. I have implemented a function that gets an object ID and returns a promise that resolves to the corresponding object, and I use `moize` to memoize the objects locally for at most 15 minutes. So far, so good. However, the web service provides _another_ method where I can submit _multiple_ IDs and the service returns _multiple_ objects, and this is more efficient if I need to query many objects at the same time. So I have created _another_ function that receives object IDs, check which ones are cached locally, retrieves the remaining ones using the web service call that supports multiple object IDs, and adds them manually to the same cache that the _first_ function uses so I can avoid caching objects multiple times. Due to the issue mentioned in the first paragraph, objects that are added manually do not expire from the cache.

I think this is not an uncommon use-case at all, so it would be great if the cache expiry mechanism could somehow be triggered for manually added items as well. Right now I can work around it by calling `expireAfter()` on the cache directly, but this API is not public.

**Comment by planttheidea** [comment]
I think I see the source of the issue, and actually this has larger implications because the same limitation exists for `maxSize` and `isPromise` handlers ... looks like the manual `add` method bypasses the standard way items are added to cache.

Let me play with this and see if I can come up with something.

**Comment by planttheidea** [comment]
Man I love partial application functions, made this super easy. Feel free to check out the PR and if you're good with it I can merge and release it right away.

**Comment by ntamas** [comment]
Seems good to me, thanks for the quick fix!

**Comment by planttheidea** [comment]
Fix has been released as `4.0.3`.
