### ISSUE TITLE
Additional target for NodeJS ES Modules (MJS)

### ISSUE THREAD

**Issue by kamronbatman** [planttheidea/moize#97]
I was hoping to use `import moize from 'moize/es` but the target looks like it is umd and not node es modules.  Would be nice to have an additional target with `.mjs` files for import with NodeJS experimental modules.

**Comment by planttheidea** [comment]
The `es` implementation was written with browser standards in mind. Based on my (admittedly limited) understanding of Node's implementation, it is the same syntax as the `es` files just with the `.mjs` file extension, correct?

**Comment by kamronbatman** [comment]
As far as I can tell you are correct.

**Comment by planttheidea** [comment]
Cool that makes it easy ... putting together a PR that does a simple copy / rename of the `es` folder output as part of the build process. Should be up shortly.

**Comment by planttheidea** [comment]
I added the PR if you wanna take a look ... seems pretty straightforward, but a fresh set of eyes is always helpful.

**Comment by kamronbatman** [comment]
I renamed the files to test and I got this error. Need to dig into it more and find out why:
> SyntaxError: The requested module does not provide an export named 'orderByLru'
    at ModuleJob._instantiate (internal/loader/ModuleJob.js:85:17)
    at <anonymous>

**Comment by kamronbatman** [comment]
I renamed those files and it looks like `deepEqual` (from fast-equals) also is not a proper mjs.  This might be more difficult than originally anticipated.

**Comment by planttheidea** [comment]
Yeah I just checked ... I think it needs to be `.mjs` turtles all the way down. Luckily, I own all of these packages (:wink:), so I can definitely add them ... but it may take a few days.

**Comment by kamronbatman** [comment]
So if I do the following:
`import memoize from 'micro-memoize/mjs';`
`import { deepEqual, sameValueZeroEqual, shallowEqual } from 'fast-equals/mjs';`

And do the rename/folder for those modules, then it loads.

**Comment by planttheidea** [comment]
Well that is good news ... at least the theory holds!

Alright well then I'll get to work doing this to those other packages, and report back here once ready to check again.

**Comment by kamronbatman** [comment]
Ohh I didn't even know about that.  Yeah it does the chore of doing a require (instead of import) and re-exporting.  Thanks!

**Comment by planttheidea** [comment]
Alright I've updated all the sub packages, and the build process to use the mjs versions. If you want to check it out, I'd appreciate the feedback.

**Comment by kamronbatman** [comment]
Sorry, I am out of town for 3 weeks. I'll check it out and get back to you.

**Comment by planttheidea** [comment]
No worries, I was actually able to verify it myself with a simple test file ... Worked as expected. This change was released as `5.4.0`.
