### ISSUE TITLE
Add git tags

### ISSUE THREAD

**Issue by ehmicky** [planttheidea/moize#99]
Could you please add git tags on new releases? This will automatically create GitHub releases, which can help users getting notified on new releases via RSS.

Thanks for this project!

**Comment by planttheidea** [comment]
I've actually been meaning to transition to using GitHub releases instead of just a changelog file, and this is the impetus I needed to do it retroactively.

I'm traveling right now, but I'll try to take care of that this weekend.

**Comment by ehmicky** [comment]
Thanks a lot! Could you please update this issue once you've done it, so I get notified?

**Comment by planttheidea** [comment]
Of course! I wouldn't leave you hanging bud. 😋

**Comment by planttheidea** [comment]
Closing because the use of `release-it` is part of my standard release process now (it's truly glorious), and I've done a couple of `moize` releases with it since.
